### ISSUE TITLE
API terms of use

### ISSUE THREAD

**Issue by derekeder** [datamade/illinois-sunshine#104]
For the API, we may want to add a section on providing credit to ICPR when making use of their API. Would be good to find some example language for this.

Related to #9

**Comment by sarahbrune** [comment]
That would be great - I'm not sure how this usually works, but could we add our contact info and ask that they reach out if they are planning to use the API? I'm not expecting people to come running to use it, but it would be nice to know if they are so we can work with them.

**Comment by fgregg** [comment]
Look here for inspiration: http://developer.nytimes.com/attribution

On Fri, Oct 16, 2015 at 3:57 PM, sarahbrune <notifications@github.com>
wrote:

> That would be great - I'm not sure how this usually works, but could we
> add our contact info and ask that they reach out if they are planning to
> use the API? I'm not expecting people to come running to use it, but it
> would be nice to know if they are so we can work with them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/illinois-sunshine/issues/104#issuecomment-148835206>
> .
>



-- 
773.888.2718

**Comment by sarahbrune** [comment]
Thoughts??

**Illinois Sunshine Attribution Guidelines**
Your use of any Illinois Sunshine API content must appropriately attribute the Illinois Campaign for Political Reform (ICPR) by name and logo usage whenever possible. You may not display the API content in such a manner that does not allow for successful linking and redirection to, and delivery of, illinoissunshine.org.

ICPR would like to work with you if you plan to use data from Illinois Sunshine. Please contact us at outreach@ilcampaign.org to discuss partnership opportunities.

Click here to get ICPR's logo for use with API data. (not sure the best way to make this available)

**Restrictions on Illinois Sunshine Data**
Unless otherwise consented to or permitted by the Illinois Campaign for Political Reform, you will:

* not modify or edit any content, headlines, links or metadata included in the API content when presenting it on your Site;

* ensure that the fundamental meaning of the API content is not changed or distorted;

* ensure that the use or display of API content does not suggest that the Illinois Campaign for Political Reform promotes or endorses you or any third party or the causes, ideas, Web sites, political candidates or parties, products or services of you or any third party;

* not display the name, logo, trademark or other identifier of another person (except for ICPR or you) on your Site in such a manner as to give the viewer the impression that such other person is a publisher or distributor of the API content on the Site

ICPR is a nonpartisan, nonprofit 501(c)3 organization, and cannot endorse or support any political party, candidate for elected office, or partisan politics. Data from Illinois Sunshine may not be used to insinuate such support.

**Comment by derekeder** [comment]
@sarahbrune this is great!

A few notes:

* I can embed the ICPR logo in this terms of use for easy use
* this will probably pour cold water on anyone wanting to use the API: "not modify or edit any content, headlines, links or metadata included in the API content when presenting it on your Site;". The goal of the API is for people to use and remix this data, not just display it verbatim.
* along the same lines "Data from Illinois Sunshine may not be used to insinuate such support." is also very limiting. Would you be ok with leaving it out?

**Comment by fgregg** [comment]
I think that the "insinuate support thing is important but already covered
by the third bullet point

**Comment by sarahbrune** [comment]
Gotcha. It's really important that people don't use our name in support of
political candidates or campaigns, so that's what I was getting at with the
insinuation thing.

I'm fine with the text in your second bullet point coming out.

**Comment by sarahbrune** [comment]
But yeah, maybe we could beef it up slightly in the third bullet point? It's important for our nonprofit status. It's almost like...if a campaign is going to use this info on their site or in a mailer or something, they shouldn't use our name at all.

Not sure what scenario this would occur in, just something I'm worried about.

**Comment by derekeder** [comment]
Ok wil do.

Can we modify your third bullet point to:

ensure that the use or display of API content does not suggest that the Illinois Campaign for Political Reform promotes or endorses you or any third party or the causes, ideas, Web sites, political candidates or parties, products or services of you or any third party. ICPR is a nonpartisan, nonprofit 501(c)3 organization, and cannot endorse or support any political party, candidate for elected office, or partisan politics;

**Comment by sarahbrune** [comment]
yes

**Comment by derekeder** [comment]
ok will do!

**Comment by derekeder** [comment]
Ok added to the site: http://illinoissunshine.org/api-documentation/#tos

@sarahbrune let me know if you want to make any additional changes.

**Comment by sarahbrune** [comment]
Looks great! Can you include this horizontal logo with the square logo? I designed it after you recommended we get one....you're right it's much more useful for web

![horizontal icpr logo](https://cloud.githubusercontent.com/assets/14282538/10847884/15ab50ec-7ee7-11e5-9899-9e80515e4f1b.png)

**Comment by derekeder** [comment]
Nice! Will do!

On Fri, Oct 30, 2015 at 9:19 AM, sarahbrune <notifications@github.com>
wrote:

> Looks great! Can you include this horizontal logo with the square logo? I
> designed it after you recommended we get one....you're right it's much more
> useful for web
>
> [image: horizontal icpr logo]
> <https://cloud.githubusercontent.com/assets/14282538/10847884/15ab50ec-7ee7-11e5-9899-9e80515e4f1b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/illinois-sunshine/issues/104#issuecomment-152538560>
> .
>



-- 
Derek Eder
@derekeder <https://twitter.com/#!/derekeder>
derek.eder@gmail.com
derekeder.com
