### ISSUE TITLE
limit / paginate search results

### ISSUE THREAD

**Issue by derekeder** [datamade/illinois-sunshine#26]
searching for 'smith' yields 18,000 results, which almost choked my browser (esp now that we have datatables on there)

**Comment by evz** [comment]
This might be tricky to make it sensible for a user since the pagination would be per term, per table (so, each grouping of records that match a given variation of "Smith" would be paginated not the whole list of results). 

One way to get around this would be to make a separate query for each table. This might slow things down for smaller result lists but I think it might end up being better overall.

**Comment by evz** [comment]
This was implemented here cd20d901420fe58a76ed87a0a4d6e8592197e796
